language: dart

dart:
  - stable

dart_task:
  - dartfmt
  - dartanalyzer: true

install:
  - git clone https://github.com/flutter/flutter.git -b stable

script:
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter test
