language: dart
dist: xenial
install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
  - gem install coveralls-lcov
script:
 - echo "export PATH=(PATH TO FLUTTER DIRECTORY)/flutter/bin:$PATH" >> $HOME/.bash_profile
 - cd gen_next_app
 - flutter test --coverage
after_success:
  - coveralls-lcov coverage/lcov.info
cache:
  directories:
    - $HOME/.pub-cache
