name: gennextapp
description: GenNext Education Application
version: 1.0.0+7

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^1.1.5
  back_button_interceptor: ^4.2.3
  datetime_picker_formfield: ^1.0.0
  http: ^0.12.0+1
  searchable_dropdown: ^1.1.3
  country_currency_pickers: ^1.0.0
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.2.0
  path_provider: ^1.6.7
  flutter_cache_manager: ^1.2.2
  table_calendar: ^2.2.3
  flutter_swiper: ^1.1.6
  zefyr:
    git:
      url: git://github.com/winwisely99/zefyr.git
      path: packages/zefyr/
      commit: 9b032d8
  quill_zefyr_bijection: ^0.3.0
  url_launcher: ^5.4.11
  percent_indicator: "^2.1.5"
  flutter_spinkit: "^4.1.2"
  checklist: ^0.1.4
  expand_widget: ^1.0.0+1
  file_picker: ^1.12.0
  dio: ^3.0.9
  clipboard_manager: ^0.0.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: maticons
      fonts:
        - asset: fonts/maticon.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Black.ttf
          weight: 900
