name: gennextapp
description: GenNext Education Application
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^1.1.5
  back_button_interceptor: ^4.2.3
  gradient_app_bar: ^0.1.3
  datetime_picker_formfield: ^1.0.0
  http: ^0.12.0+1
  searchable_dropdown: ^1.1.3
  country_currency_pickers: ^1.0.0
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.2.0
  path_provider: ^1.6.7
  flutter_cache_manager: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
  - images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
