on: push
name: Test
jobs:
  build:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Start Simulator
      run: xcrun simctl boot 373EB035-CACF-4FC7-8D58-B12CC24F5333
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.0'
    - run: flutter pub get
    - name: Run Flutter Widget Tests
      run: flutter test
    - name: Run Flutter Integration Tests
      run: flutter drive --target=test_driver/app.dart
