on: push
name: Test
jobs:
  build:
    strategy:
      matrix:
        device:
         - 61BB25F8-AFA7-460B-8E2F-6EB5BD7C1E24
         - BBAA1D88-F2BA-4BB1-AFC9-F4DDF29003C0
    name: Test
    runs-on: macos-latest
    steps:
    - name: List all simulators
      run: xcrun instruments -s
    - name: "Start Simulator"
      run: xcrun simctl boot ${{matrix.device}}
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.0'
    - run: flutter pub get
    - name: Run Flutter Widget Tests
      run: flutter test
    - name: Run Flutter Integration Tests
      run: flutter drive --target=test_driver/app.dart
